In [3]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, utils
from sklearn.utils import shuffle

# Loading Data

In [2]:
df = pd.read_csv('data/compresive_strength_concrete.csv')
df.head()

Cement (component 1)(kg in a m^3 mixture)  \
0                                      540.0   
1                                      540.0   
2                                      332.5   
3                                      332.5   
4                                      198.6   

   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                0.0       
1                                                0.0       
2                                              142.5       
3                                              142.5       
4                                              132.4       

   Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   Water  (component 4)(kg in a m^3 mixture)  \
0                                      162.0   
1                                      162.0   
2                                      228.0   
3                                      228.0   
4                                      192.0   

   Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                2.5     
1                                                2.5     
2                                                0.0     
3                                                0.0     
4                                                0.0     

   Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                             1040.0      
1                                             1055.0      
2                                              932.0      
3                                              932.0      
4                                              978.4      

   Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                              676.0         28   
1                                              676.0         28   
2                                              594.0        270   
3                                              594.0        365   
4                                              825.5        360   

   Concrete compressive strength(MPa, megapascals)   
0                                             79.99  
1                                             61.89  
2                                             40.27  
3                                             41.05  
4                                             44.30

In [24]:
#checking for null values
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Cement (component 1)(kg in a m^3 mixture), Blast Furnace Slag (component 2)(kg in a m^3 mixture), Fly Ash (component 3)(kg in a m^3 mixture), Water  (component 4)(kg in a m^3 mixture), Superplasticizer (component 5)(kg in a m^3 mixture), Coarse Aggregate  (component 6)(kg in a m^3 mixture), Fine Aggregate (component 7)(kg in a m^3 mixture), Age (day), Concrete compressive strength(MPa, megapascals) ]
Index: []

In [4]:
data = shuffle(df)
data.head()

Cement (component 1)(kg in a m^3 mixture)  \
782                                      296.0   
21                                       139.6   
16                                       139.6   
855                                      326.0   
682                                      183.9   

     Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
782                                                0.0       
21                                               209.4       
16                                               209.4       
855                                              166.0       
682                                              122.6       

     Fly Ash (component 3)(kg in a m^3 mixture)  \
782                                         0.0   
21                                          0.0   
16                                          0.0   
855                                         0.0   
682                                         0.0   

     Water  (component 4)(kg in a m^3 mixture)  \
782                                      192.0   
21                                       192.0   
16                                       192.0   
855                                      174.0   
682                                      203.5   

     Superplasticizer (component 5)(kg in a m^3 mixture)  \
782                                                0.0     
21                                                 0.0     
16                                                 0.0     
855                                                9.0     
682                                                0.0     

     Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
782                                             1085.0      
21                                              1047.0      
16                                              1047.0      
855                                              882.0      
682                                              959.2      

     Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
782                                              765.0         28   
21                                               806.9         28   
16                                               806.9         90   
855                                              790.0         28   
682                                              800.0         28   

     Concrete compressive strength(MPa, megapascals)   
782                                             21.65  
21                                              28.24  
16                                              39.36  
855                                             61.23  
682                                             24.05

In [5]:
data = data.values
print(data)

[[296.     0.     0.   ... 765.    28.    21.65]
 [139.6  209.4    0.   ... 806.9   28.    28.24]
 [139.6  209.4    0.   ... 806.9   90.    39.36]
 ...
 [359.    19.   141.   ... 801.    28.    62.94]
 [154.8  183.4    0.   ... 696.7   28.    18.29]
 [144.   170.   133.   ... 805.    28.    29.87]]


In [6]:
data.shape

(1030, 9)

# Splitting Data

In [55]:
#splitting labels from data
x = data[:,:8].astype('float32')
y = data[:,8]
print(x[0])
print(y[0])

[ 296.    0.    0.  192.    0. 1085.  765.   28.]
21.65


In [56]:
print(x.shape)
print(y.shape)

(1030, 8)
(1030,)


In [57]:
#splitting data for training, testing and validation
train_data = x[:515,:] #50% for training
train_labels = y[:515]
val_data = x[515:721,:] # 20% for validation
val_labels = y[515:721]
test_data = x[721:,:] # 30% for testing
test_label = y[721:]

In [58]:
print('Train data: ',train_data.shape)
print('Validation data: ',val_data.shape)
print('Test data: ',test_data.shape)

Train data:  (515, 8)
Validation data:  (206, 8)
Test data:  (309, 8)


# Building Model

In [77]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(8,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1))

# Compiling Model

In [78]:
model.compile(optimizer='rmsprop',
              loss='mse',
              metrics=['mae'])

In [79]:
history = model.fit(train_data, train_labels, epochs=100, batch_size=4, validation_data=(val_data,val_labels))

Train on 515 samples, validate on 206 samples
Epoch 1/100
515/515 [==============================] - 2s 5ms/sample - loss: 302.1392 - mae: 13.9467 - val_loss: 253.3951 - val_mae: 12.8345
Epoch 2/100
515/515 [==============================] - 1s 1ms/sample - loss: 243.8940 - mae: 12.5339 - val_loss: 213.2562 - val_mae: 12.0227
Epoch 3/100
515/515 [==============================] - 1s 1ms/sample - loss: 223.9423 - mae: 12.1523 - val_loss: 246.3447 - val_mae: 12.7102
Epoch 4/100
515/515 [==============================] - 1s 1ms/sample - loss: 199.5974 - mae: 11.3562 - val_loss: 162.1519 - val_mae: 9.8875
Epoch 5/100
515/515 [==============================] - 1s 1ms/sample - loss: 171.8977 - mae: 10.4317 - val_loss: 593.1549 - val_mae: 21.4532
Epoch 6/100
515/515 [==============================] - 1s 1ms/sample - loss: 170.5187 - mae: 10.4443 - val_loss: 170.4032 - val_mae: 10.1896
Epoch 7/100
515/515 [==============================] - 1s 1ms/sample - loss: 168.4454 - mae: 10.2226 - val_lo

Epoch 59/100
515/515 [==============================] - 1s 1ms/sample - loss: 61.2512 - mae: 5.9448 - val_loss: 88.5900 - val_mae: 7.4354
Epoch 60/100
515/515 [==============================] - 0s 962us/sample - loss: 58.7236 - mae: 5.8703 - val_loss: 59.0271 - val_mae: 6.0244
Epoch 61/100
515/515 [==============================] - 1s 1ms/sample - loss: 57.7935 - mae: 5.7975 - val_loss: 107.7041 - val_mae: 8.5470
Epoch 62/100
515/515 [==============================] - 0s 939us/sample - loss: 55.3630 - mae: 5.7129 - val_loss: 55.7722 - val_mae: 5.8323
Epoch 63/100
515/515 [==============================] - 0s 893us/sample - loss: 58.1862 - mae: 5.7404 - val_loss: 49.6157 - val_mae: 5.3664
Epoch 64/100
515/515 [==============================] - 0s 919us/sample - loss: 55.8426 - mae: 5.6456 - val_loss: 54.5393 - val_mae: 5.6609
Epoch 65/100
515/515 [==============================] - 0s 927us/sample - loss: 53.9750 - mae: 5.7380 - val_loss: 62.8950 - val_mae: 6.0098
Epoch 66/100
515/515 [=

In [80]:
mse, mae = model.evaluate(test_data,test_label, verbose=2)

309/1 - 0s - loss: 71.2554 - mae: 5.6181


In [69]:
mae

5.541106

# Prediction

In [53]:
i = 10
prediction = model.predict(test_data[i].reshape(1,8))

In [54]:
print(f'Data = {test_data[i]} => Predicted Value = {prediction}')
print(f'Data = {test_data[i]} => Actual Value    = {test_label[i]}')

Data = [531.3   0.    0.  141.8  28.2 852.1 893.7   3. ] => Predicted Value = [[40.686344]]
Data = [531.3   0.    0.  141.8  28.2 852.1 893.7   3. ] => Actual Value    = 41.3
