# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

In [1]:
import tensorflow as tf
from tensorflow.keras import layers , optimizers , layers , models
from tensorflow.keras.utils import to_categorical
from sklearn.utils import shuffle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [2]:
data = pd.read_csv('iris.csv')
#shuffling data
data = shuffle(data)
df = data.values
df

array([[6.0, 2.7, 5.1, 1.6, 'Versicolor'],
       [5.5, 4.2, 1.4, 0.2, 'Setosa'],
       [5.8, 2.7, 5.1, 1.9, 'Virginica'],
       [6.5, 3.0, 5.5, 1.8, 'Virginica'],
       [6.3, 2.5, 5.0, 1.9, 'Virginica'],
       [4.8, 3.4, 1.9, 0.2, 'Setosa'],
       [6.1, 2.8, 4.0, 1.3, 'Versicolor'],
       [5.6, 2.5, 3.9, 1.1, 'Versicolor'],
       [5.4, 3.4, 1.5, 0.4, 'Setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Setosa'],
       [6.9, 3.1, 5.4, 2.1, 'Virginica'],
       [7.7, 2.8, 6.7, 2.0, 'Virginica'],
       [5.7, 3.8, 1.7, 0.3, 'Setosa'],
       [5.5, 2.5, 4.0, 1.3, 'Versicolor'],
       [6.1, 2.9, 4.7, 1.4, 'Versicolor'],
       [5.4, 3.9, 1.3, 0.4, 'Setosa'],
       [5.1, 2.5, 3.0, 1.1, 'Versicolor'],
       [6.0, 2.9, 4.5, 1.5, 'Versicolor'],
       [6.7, 3.3, 5.7, 2.1, 'Virginica'],
       [5.8, 2.7, 4.1, 1.0, 'Versicolor'],
       [5.0, 3.6, 1.4, 0.2, 'Setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Setosa'],
       [6.4, 3

In [3]:
df.shape

(150, 5)

In [4]:
data.head()
data.shape

(150, 5)

In [5]:
#spliting data

#training 70%
x_train = df[:105,:4].astype('float32')
y_train = df[:105,4]   #label or output

#testing 30%
x_test = df[105:,:4].astype('float32')
y_test = df[105:,4]  #label or output

In [6]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((105, 4), (105,), (45, 4), (45,))

### STEP 2.1 : ENCODING

In [7]:
from sklearn.preprocessing import LabelEncoder
# encode class values as integers

#training
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
print(y_train)
one_hot_encode_train = to_categorical(y_train)

print('\n')

#testing
le.fit(y_test)
y_test = le.transform(y_test)
print(y_test)
one_hot_encode_test = to_categorical(y_test)

[1 0 2 2 2 0 1 1 0 0 2 2 0 1 1 0 1 1 2 1 0 0 0 0 2 0 0 2 0 2 2 1 2 0 1 1 0
 0 2 1 1 2 1 2 1 1 1 1 2 1 1 1 1 2 2 1 0 1 1 2 0 0 2 0 2 1 2 0 0 1 2 1 2 2
 0 0 1 2 1 2 1 2 0 2 1 1 0 2 2 0 0 1 0 0 1 0 2 2 0 2 0 0 1 0 1]


[0 2 2 2 2 0 2 0 1 2 0 0 1 1 0 2 0 0 1 0 1 2 2 1 0 1 2 2 0 2 0 0 2 1 2 2 2
 1 1 0 1 1 1 2 0]


In [8]:
le.classes_

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [9]:
one_hot_encode_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [10]:
one_hot_encode_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [11]:
model = models.Sequential()
model.add(layers.Dense(8 , input_shape = (4,) , activation = 'relu'))
model.add(layers.Dense(3 ,  activation = 'softmax'))

### STEP 4 : Compilation Step 

In [12]:
model.compile(optimizer = 'rmsprop',
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])
history = model.fit(x_train , one_hot_encode_train , epochs = 40 ,batch_size = 4)

Train on 105 samples
Epoch 1/40
105/105 [==============================] - 2s 20ms/sample - loss: 1.7324 - accuracy: 0.3524
Epoch 2/40
105/105 [==============================] - 0s 685us/sample - loss: 1.4976 - accuracy: 0.3524
Epoch 3/40
105/105 [==============================] - 0s 752us/sample - loss: 1.3497 - accuracy: 0.3524
Epoch 4/40
105/105 [==============================] - 0s 685us/sample - loss: 1.2394 - accuracy: 0.3619
Epoch 5/40
105/105 [==============================] - 0s 609us/sample - loss: 1.1444 - accuracy: 0.4952
Epoch 6/40
105/105 [==============================] - 0s 657us/sample - loss: 1.0756 - accuracy: 0.5619
Epoch 7/40
105/105 [==============================] - 0s 771us/sample - loss: 1.0176 - accuracy: 0.4667
Epoch 8/40
105/105 [==============================] - 0s 761us/sample - loss: 0.9685 - accuracy: 0.3619
Epoch 9/40
105/105 [==============================] - 0s 676us/sample - loss: 0.9273 - accuracy: 0.3143
Epoch 10/40
105/105 [=======================

### STEP 5 : Evaluation 

In [13]:
result = model.evaluate(x_test , one_hot_encode_test , verbose = 2)

45/1 - 0s - loss: 0.4856 - accuracy: 0.9333


In [14]:
result

[0.4584348334206475, 0.93333334]

### STEP 6 : Prediction 

In [29]:
i=10
prediction = model.predict_classes(x_test[8].reshape(1,4))

In [30]:
#checking
if prediction == 0:
    print(f'Data = {x_test[i]} => Prediction = Setosa => Actual label = {x_test[i]}')
elif prediction == 1:
    print(f'Data = {x_test[i]} => Prediction = Versicolor => Actual label = {x_test[i]}')
else:
     print(f'Data = {x_test[i]} => Prediction = Virginica => Actual label = {x_test[i]}')

Data = [5.  3.4 1.5 0.2] => Prediction = Versicolor => Actual label = [5.  3.4 1.5 0.2]
